config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'tops/index'
  root "tops#index"
  resources :profiles do
    resources :votes, only: [:create]
    resources :result, only: [:index]
  end
  resources :thanks, only: [:index] do
    resources :messages, only: [:index, :create]
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_many :votes
  has_many :voted_users, through: :votes, source: :user
  has_one_attached :image
  has_many :messages
  has_many :thanks

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :birth
  belongs_to_active_hash :marry
  belongs_to_active_hash :money
  belongs_to_active_hash :school
  belongs_to_active_hash :sex
  belongs_to_active_hash :smoke
  belongs_to_active_hash :drink
  belongs_to_active_hash :live
  belongs_to_active_hash :occupation

  with_options presence: true do
    validates :image
    validates :nickname
    validates :hobby
    validates :birthday
    validates :info
    validates :salary,    numericality: { with: /\A[0-9]+\z/, message: 'Half-width number' }
    end

  with_options numericality: { other_than: 0, message: 'Select'  } do
    validates :birth_id
    validates :school_id
    validates :sex_id 
    validates :smoke_id 
    validates :marry_id
    validates :money_id 
    validates :occupation_id
    validates :drink_id
    validates :live_id 
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
    if current_user.sex_id == 1
      @profiles = Profile.where(sex_id: 2).shuffle
    else
      @profiles = Profile.where(sex_id: 1).shuffle
    end
  end

  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(profile_params)
    if current_user.sex_id != @profile.sex_id
      redirect_to  new_profile_path
    else
      if @profile.save
        redirect_to  profiles_path
      else
        render :new
      end
    end
  end

  def show
    @profile = Profile.find(params[:id])
    @users = @profile.voted_users.order("created_at DESC")
    @vote = Vote.new
  end

  def edit
    if params[:id].to_i == current_user.profile.id
      @profile = Profile.find(params[:id])
    else
      redirect_to  profiles_path
    end
  end

  def update
    @profile = Profile.find(params[:id])
    if @profile.update(profile_params)
      redirect_to  profiles_path
    else
      render :edit
    end
  end

  def destroy
    @profile = Profile.find(params[:id])
    if user_signed_in? && current_user.id == @profile.user_id
      @profile.destroy
      redirect_to  root_path
    else
      render :index
    end
  end

  private
  def profile_params
    params.require(:profile).permit(:image, :nickname, :hobby, :birthday, :birth_id, :school_id, :salary, :sex_id, :smoke_id, :marry_id, :money_id, :info, :occupation_id, :drink_id, :live_id).merge(user_id: current_user.id)
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/edit.html.erb
<div class = "new-title-area">
<h1 class = "new-title">プロフィール作成<h1>
</div>
<div class = "back-title">
  <%= link_to "戻る", profiles_path %>
</div>

<%= form_with model: @profile, local: true do |f| %>

<%= render 'shared/error_messages', model: f.object %>

<div class = "all-profile">
   <div class = "image">
     <div class = "image-title">
        <label class="form-text">写真をアップロード</label>
     </div>
     <div class = "image-select">
        <%= f.file_field :image, id:"comment-image" %>
    </div>
   </div>
   <br>
  <div class = "nickname-hobby">
     <div class = "nickname">
       <label class="form-text">ニックネーム</label><br>
       <%= f.text_field :nickname, class: "profile-nickname" %>
     </div>
     <div class = "hobby">
       <label class="form-text">趣味</label><br>
       <%= f.text_field :hobby, class: "profile-hobby" %>
     </div>
     <div class='birth'>
       <label class="form-text">生年月日</label><br>
       <%= raw sprintf(
                  f.date_select(
                    :birthday,
                    class:'select-birth',
                    id:"birth-date",
                    use_month_numbers: true,
                    prompt:'--',
                    start_year: 1940,
                    end_year: (Time.now.year - 20),
                    date_separator: '%s'),
                  " 年 ", " 月 ") + " 日 " %>
    </div>
  </div>
  <br>
  <div class = "birth-salary">
    <div class = "birth">
      <label class="form-text">出身</label>
      <%= f.collection_select(:birth_id, Birth.all, :id, :name, {}, {class:"profile-box", id:"item-scheduled-delivery"}) %>
    </div>
    <div class = "live">
    <label class="form-text">住所</label>
    <%= f.collection_select(:live_id, Live.all, :id, :name, {}, {class:"profile-box", id:"item-scheduled-delivery"}) %>
    </div>
    <div class = "school">
    <label class="form-text">学歴</label>
    <%= f.collection_select(:school_id, School.all, :id, :name, {}, {class:"profile-box", id:"item-scheduled-delivery"}) %>
    </div>
    <div class = "occupation">
    <label class="form-text">職業</label>
    <%= f.collection_select(:occupation_id, Occupation.all, :id, :name, {}, {class:"occupation-box", id:"item-scheduled-delivery"}) %>
    </div>
    <div class = "salary">
      <label class="form-text">給料</label><br>
      <%= f.text_field :salary, class: "salary-text" %>万円
    </div>
  </div>
  <br>
  <div class = "drink-money">
    <div class = "drink">
    <label class="form-text">飲酒</label>
    <%= f.collection_select(:drink_id, Drink.all, :id, :name, {}, {class:"profile-box", id:"item-scheduled-delivery"}) %>
    </div>
    <div class = "smoke">
    <label class="form-text">タバコ</label>
    <%= f.collection_select(:smoke_id, Smoke.all, :id, :name, {}, {class:"profile-box", id:"item-scheduled-delivery"}) %>
    </div>
    <div class = "marry">
    <label class="form-text">婚姻歴</label>
    <%= f.collection_select(:marry_id, Marry.all, :id, :name, {}, {class:"profile-box", id:"item-scheduled-delivery"}) %>
    </div>
    <div class = "sex">
    <label class="form-text">性別</label>
    <%= f.collection_select(:sex_id, Sex.all, :id, :name, {}, {class:"profile-box", id:"item-scheduled-delivery"}) %>
    </div>
    <div class = "money">
    <label class="form-text">会員</label>
    <%= f.collection_select(:money_id, Money.all, :id, :name, {}, {class:"profile-box", id:"item-scheduled-delivery"}) %>
    </div>
  </div>
  <br>
   <div class = "message">
    <label class="form-text">自己紹介</label><br>
    <%= f.text_area :info, class:"comments-text", id:"comment-text", placeholder:"自己紹介文を書きましょう(1,000文字まで)" ,rows:"7" ,maxlength:"1000" %>
   </div>
   <div class = "message-btn">
     <%= f.submit "登録する" ,class:"sell-btn" %>
   </div>
</div>
</div>
<% end %>

app/views/profiles/index.html.erb
<% if current_user.sex_id == 1 %>
<h1 class = "index-title">女性会員一覧</h1>
<% else %>
<h1 class = "index-title">男性会員一覧</h1>
<% end %>

<div class = "profile-back">
  <div class = "change">
    <%= link_to "マイページ", profile_path(current_user.profile.id), method: :get %>
  </div>
  <div class = "change">
  <%= link_to "プロフィールを変更する", edit_profile_path(current_user.profile.id), class: "profile-post" %>
  </div>
  <div class = "change">
    <%= link_to "成立した人", profile_result_index_path(current_user.profile.id), method: :get %>
  </div>
     <% if current_user.profile.money_id == 2 %>
       <div class = "change">
        <%= link_to "メッセージ", thanks_path %>
      </div>
      <% end %>
  <div class = "change">
    <%= link_to "戻る", root_path, class: "back-root" %>
  </div>
</div>

<div class = "user-profiles">
  <% @profiles.each do |profile| %>
     <div class = "users-image">
       <div class = "images-top">
         <%= image_tag profile.image, size: '300x300' %>
      </div>
       <div><%=  profile.nickname %></div>
       <div><%= link_to "この会員のプロフィールを見る", profile_path(profile.id) %></div>
    </div>
  <% end %>
</div>

app/views/profiles/new.html.erb
<div class = "new-title-area">
<h1 class = "new-title">プロフィール作成<h1>
</div>
<div class = "back-title">
  <%= link_to "戻る", root_path %>
</div>

<%= form_with model: @profile, local: true do |f| %>

<%= render 'shared/error_messages', model: f.object %>

<div class = "all-profile">
   <div class = "image">
     <div class = "image-title">
        <label class="form-text">写真をアップロード</label>
     </div>
     <div class = "image-select">
        <%= f.file_field :image, id:"comment-image" %>
    </div>
   </div>
   <br>
  <div class = "nickname-hobby">
     <div class = "nickname">
       <label class="form-text">ニックネーム</label><br>
       <%= f.text_field :nickname, class: "profile-nickname" %>
     </div>
     <div class = "hobby">
       <label class="form-text">趣味</label><br>
       <%= f.text_field :hobby, class: "profile-hobby" %>
     </div>
     <div class='birth'>
       <label class="form-text">生年月日</label><br>
       <%= raw sprintf(
                  f.date_select(
                    :birthday,
                    class:'select-birth',
                    id:"birth-date",
                    use_month_numbers: true,
                    prompt:'--',
                    start_year: 1940,
                    end_year: (Time.now.year - 20),
                    date_separator: '%s'),
                  " 年 ", " 月 ") + " 日 " %>
    </div>
  </div>
  <br>
  <div class = "birth-salary">
    <div class = "birth">
      <label class="form-text">出身</label>
      <%= f.collection_select(:birth_id, Birth.all, :id, :name, {}, {class:"profile-box", id:"item-scheduled-delivery"}) %>
    </div>
    <div class = "live">
    <label class="form-text">住所</label>
    <%= f.collection_select(:live_id, Live.all, :id, :name, {}, {class:"profile-box", id:"item-scheduled-delivery"}) %>
    </div>
    <div class = "school">
    <label class="form-text">学歴</label>
    <%= f.collection_select(:school_id, School.all, :id, :name, {}, {class:"profile-box", id:"item-scheduled-delivery"}) %>
    </div>
    <div class = "occupation">
    <label class="form-text">職業</label>
    <%= f.collection_select(:occupation_id, Occupation.all, :id, :name, {}, {class:"occupation-box", id:"item-scheduled-delivery"}) %>
    </div>
    <div class = "salary">
      <label class="form-text">給料</label><br>
      <%= f.text_field :salary, class: "salary-text" %>万円
    </div>
  </div>
  <br>
  <div class = "drink-money">
    <div class = "drink">
    <label class="form-text">飲酒</label>
    <%= f.collection_select(:drink_id, Drink.all, :id, :name, {}, {class:"profile-box", id:"item-scheduled-delivery"}) %>
    </div>
    <div class = "smoke">
    <label class="form-text">タバコ</label>
    <%= f.collection_select(:smoke_id, Smoke.all, :id, :name, {}, {class:"profile-box", id:"item-scheduled-delivery"}) %>
    </div>
    <div class = "marry">
    <label class="form-text">婚姻歴</label>
    <%= f.collection_select(:marry_id, Marry.all, :id, :name, {}, {class:"profile-box", id:"item-scheduled-delivery"}) %>
    </div>
    <div class = "sex">
    <label class="form-text">性別</label>
    <%= f.collection_select(:sex_id, Sex.all, :id, :name, {}, {class:"profile-box", id:"item-scheduled-delivery"}) %>
    </div>
    <div class = "money">
    <label class="form-text">会員</label>
    <%= f.collection_select(:money_id, Money.all, :id, :name, {}, {class:"profile-box", id:"item-scheduled-delivery"}) %>
    </div>
  </div>
  <br>
   <div class = "message">
    <label class="form-text">自己紹介</label><br>
    <%= f.text_area :info, class:"comments-text", id:"comment-text", placeholder:"自己紹介文を書きましょう(1,000文字まで)" ,rows:"7" ,maxlength:"1000" %>
   </div>
   <div class = "message-btn">
     <%= f.submit "登録する" ,class:"sell-btn" %>
   </div>
</div>
</div>
<% end %>

app/views/profiles/show.html.erb
<h1 class = "show-title">プロフィール詳細<h1>
<div class = "back-title">
  <%= link_to "戻る", profiles_path %>
</div>

<div class = "show-image">
   <%= image_tag @profile.image, size: '300x300' %>
</div>

<table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item1">自己紹介</th>
          <td class="detail-value1"><%= @profile.info %></td>
        </tr>
        <tr>
          <th class="detail-item">ニックネーム</th>
          <td class="detail-value"><%= @profile.nickname %></td>
        </tr>
        <tr>
          <th class="detail-item">趣味</th>
          <td class="detail-value"><%= @profile.hobby %></td>
        </tr>
        <tr>
          <th class="detail-item">生年月日</th>
          <td class="detail-value"><%= @profile.birthday %></td>
        </tr>
        <tr>
          <th class="detail-item">出身</th>
          <td class="detail-value"><%= @profile.birth.name %></td>
        </tr>
        <tr>
          <th class="detail-item">現在の住所</th>
          <td class="detail-value"><%= @profile.live.name %></td>
        </tr>
        <tr>
          <th class="detail-item">学歴</th>
          <td class="detail-value"><%= @profile.school.name %></td>
        </tr>
        <tr>
          <th class="detail-item">職業</th>
          <td class="detail-value"><%= @profile.occupation.name %></td>
        </tr>
        <tr>
          <th class="detail-item">給料</th>
          <td class="detail-value"><%= @profile.salary %>万円</td>
        </tr>
        <tr>
          <th class="detail-item">飲酒</th>
          <td class="detail-value"><%= @profile.drink.name %></td>
        </tr>
        <tr>
          <th class="detail-item">タバコ</th>
          <td class="detail-value"><%= @profile.smoke.name %></td>
        </tr>
        <tr>
          <th class="detail-item">婚姻歴</th>
          <td class="detail-value"><%= @profile.marry.name %></td>
        </tr>
      </tbody>
</table>
<% if @profile.user.id != current_user.id %>
  <div class = "button">
   <% if current_user.already_voted?(@profile) %>
      <div class = "result">
         <%= 'いいね済み' %>
      </div>
   <% else %>
     <%= button_to 'いいね', profile_votes_path(@profile), class: "btn-size" %>
   <% end %>
  </div>
<%  else %>
  <h2 class = "result">いいねした人</h2>
  <% @users.each do |user| %>
   <div class = "vote-list">
   <% if user.profile.present? %>
     <div><%= link_to user.profile.nickname, profile_path(user.profile.id) %></div>
     <div><%= image_tag user.profile.image, size: '300x300' %></div>
   <% end %>
  </div>
   <% end %>
<% end %>